apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pods.master.secret.name }}
type: Opaque
stringData:
  prod.conf: |-
    include "application.conf"

    play.http.secret.key="{{ .Values.pods.master.http.secret }}"
